// Code generated by goctl. DO NOT EDIT.

package tTrainStation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTrainStationFieldNames          = builder.RawFieldNames(&TTrainStation{})
	tTrainStationRows                = strings.Join(tTrainStationFieldNames, ",")
	tTrainStationRowsExpectAutoSet   = strings.Join(stringx.Remove(tTrainStationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTrainStationRowsWithPlaceHolder = strings.Join(stringx.Remove(tTrainStationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cache12306TicketTTrainStationIdPrefix = "cache:12306Ticket:tTrainStation:id:"
)

type (
	tTrainStationModel interface {
		Insert(ctx context.Context, data *TTrainStation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTrainStation, error)
		Update(ctx context.Context, data *TTrainStation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTrainStationModel struct {
		sqlc.CachedConn
		table string
	}

	TTrainStation struct {
		Id            int64          `db:"id"`             // ID
		TrainId       sql.NullInt64  `db:"train_id"`       // 车次ID
		StationId     sql.NullInt64  `db:"station_id"`     // 车站ID
		Sequence      sql.NullString `db:"sequence"`       // 站点顺序
		Departure     sql.NullString `db:"departure"`      // 出发站点
		Arrival       sql.NullString `db:"arrival"`        // 到达站点
		StartRegion   sql.NullString `db:"start_region"`   // 起始城市
		EndRegion     sql.NullString `db:"end_region"`     // 终点城市
		ArrivalTime   sql.NullTime   `db:"arrival_time"`   // 到站时间
		DepartureTime sql.NullTime   `db:"departure_time"` // 出站时间
		StopoverTime  sql.NullInt64  `db:"stopover_time"`  // 停留时间，单位分
		CreateTime    sql.NullTime   `db:"create_time"`    // 创建时间
		UpdateTime    sql.NullTime   `db:"update_time"`    // 修改时间
		DelFlag       sql.NullInt64  `db:"del_flag"`       // 删除标识
	}
)

func newTTrainStationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTrainStationModel {
	return &defaultTTrainStationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_train_station`",
	}
}

func (m *defaultTTrainStationModel) Delete(ctx context.Context, id int64) error {
	_12306TicketTTrainStationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, _12306TicketTTrainStationIdKey)
	return err
}

func (m *defaultTTrainStationModel) FindOne(ctx context.Context, id int64) (*TTrainStation, error) {
	_12306TicketTTrainStationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationIdPrefix, id)
	var resp TTrainStation
	err := m.QueryRowCtx(ctx, &resp, _12306TicketTTrainStationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTrainStationModel) Insert(ctx context.Context, data *TTrainStation) (sql.Result, error) {
	_12306TicketTTrainStationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTrainStationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TrainId, data.StationId, data.Sequence, data.Departure, data.Arrival, data.StartRegion, data.EndRegion, data.ArrivalTime, data.DepartureTime, data.StopoverTime, data.DelFlag)
	}, _12306TicketTTrainStationIdKey)
	return ret, err
}

func (m *defaultTTrainStationModel) Update(ctx context.Context, data *TTrainStation) error {
	_12306TicketTTrainStationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTrainStationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TrainId, data.StationId, data.Sequence, data.Departure, data.Arrival, data.StartRegion, data.EndRegion, data.ArrivalTime, data.DepartureTime, data.StopoverTime, data.DelFlag, data.Id)
	}, _12306TicketTTrainStationIdKey)
	return err
}

func (m *defaultTTrainStationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache12306TicketTTrainStationIdPrefix, primary)
}

func (m *defaultTTrainStationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTrainStationModel) tableName() string {
	return m.table
}
