// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ticketOrder "go-zero-12306/app/order-service/cmd/api/internal/handler/ticketOrder"
	"go-zero-12306/app/order-service/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ticket/query",
				Handler: ticketOrder.QueryTicketOrderByOrderSnHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/item/ticket/query",
				Handler: ticketOrder.QueryTicketItemOrderByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ticket/page",
				Handler: ticketOrder.PageTicketOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ticket/self/page",
				Handler: ticketOrder.PageSelfTicketOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ticket/create",
				Handler: ticketOrder.CreateTicketOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ticket/close",
				Handler: ticketOrder.CancelTicketOrderReqHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ticket/cancel",
				Handler: ticketOrder.CancelTickOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/order-service/order"),
	)
}
