// Code generated by goctl. DO NOT EDIT.
package types

type PayReq struct {
	OutOrderSn  string  `json:"outOrderSn"`  // 子订单号
	TotalAmount float64 `json:"totalAmount"` //订单总金额,单位为元，精确到小数点后两位，取值范围：[0.01,100000000]
	Subject     string  `json:"subject"`     // 订单标题 ，注意：不可使用特殊字符，如 /，=，& 等
}

type PayResp struct {
	Body string `json:"body"` // 调用支付返回信息
}

type GetPayInfoByOrderSnReq struct {
	OrderSn string `json:"orderSn"` //订单号
}

type GetPayInfoByOrderSnResp struct {
	OrderSn     string `json:"orderSn"`     //订单号
	TotalAmount int64  `json:"totalAmount"` // 支付总金额
	Status      int64  `json:"status"`      // 支付状态
	GmtPayment  string `json:"gmtPayment"`  // 支付时间
}

type GetPayInfoByPaySnReq struct {
	PaySn string `json:"paySn"` // 支付流水号
}

type GetPayInfoByPaySnResp struct {
	OrderSn     string `json:"orderSn"`     //订单号
	TotalAmount int64  `json:"totalAmount"` // 支付总金额
	Status      int64  `json:"status"`      // 支付状态
	GmtPayment  string `json:"gmtPayment"`  // 支付时间
}

type RefundReq struct {
	OrderSn                string                              `json:"orderSn"`        // 订单号
	RefundTypeEnum         string                              `json:"refundTypeEnum"` // 退款类型枚举 （生成代码后修改）
	RefundAmount           int64                               `json:"refundAmount"`   // 退款金额
	RefundDetailReqDTOList []TicketOrderPassengerDetailRespDTO `json:"refundDetailReqDtoList"`
}

type RefundResp struct {
}

type TicketOrderPassengerDetailRespDTO struct {
	UserId         int64  `json:"userId"`         //用户id
	Username       string `json:"username"`       // 用户名
	SeatType       int64  `json:"seatType"`       // 席别类型
	CarriageNumber string `json:"carriageNumber"` //车厢号
	SeatNumber     string `json:"seatNumber"`     //座位号
	RealName       string `json:"realName"`       // 真实姓名
	IdType         string `json:"idType"`         // 证件类型
	IdCard         string `json:"idCard"`         // 证件号
	TicketType     int64  `json:"ticketType"`     // 车票类型 0：成人 1：儿童 2：学生 3：残疾军人
	Amount         int64  `json:"amount"`         // 订单金额
	Status         int64  `json:"status"`         // 车票状态
}

type CallbackAlipayReq struct {
}

type CallbackAlipayResp struct {
}
