// Code generated by goctl. DO NOT EDIT.
// Source: ticket.proto

package ticket

import (
	"context"

	"go-zero-12306/app/ticket-service/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListTrainStationQueryReq  = pb.ListTrainStationQueryReq
	ListTrainStationQueryResp = pb.ListTrainStationQueryResp
	TrainStationQueryRespDTO  = pb.TrainStationQueryRespDTO

	Ticket interface {
		ListTrainStationQuery(ctx context.Context, in *ListTrainStationQueryReq, opts ...grpc.CallOption) (*ListTrainStationQueryResp, error)
	}

	defaultTicket struct {
		cli zrpc.Client
	}
)

func NewTicket(cli zrpc.Client) Ticket {
	return &defaultTicket{
		cli: cli,
	}
}

func (m *defaultTicket) ListTrainStationQuery(ctx context.Context, in *ListTrainStationQueryReq, opts ...grpc.CallOption) (*ListTrainStationQueryResp, error) {
	client := pb.NewTicketClient(m.cli.Conn())
	return client.ListTrainStationQuery(ctx, in, opts...)
}
