// Code generated by goctl. DO NOT EDIT.
// Source: ticket.proto

package server

import (
	"context"

	"go-zero-12306/app/ticket-service/cmd/rpc/internal/logic"
	"go-zero-12306/app/ticket-service/cmd/rpc/internal/svc"
	"go-zero-12306/app/ticket-service/cmd/rpc/pb"
)

type TicketServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTicketServer
}

func NewTicketServer(svcCtx *svc.ServiceContext) *TicketServer {
	return &TicketServer{
		svcCtx: svcCtx,
	}
}

func (s *TicketServer) ListTrainStationQuery(ctx context.Context, in *pb.ListTrainStationQueryReq) (*pb.ListTrainStationQueryResp, error) {
	l := logic.NewListTrainStationQueryLogic(ctx, s.svcCtx)
	return l.ListTrainStationQuery(in)
}

func (s *TicketServer) ListRegionStation(ctx context.Context, in *pb.ListRegionStationReq) (*pb.ListRegionStationResp, error) {
	l := logic.NewListRegionStationLogic(ctx, s.svcCtx)
	return l.ListRegionStation(in)
}

func (s *TicketServer) ListAllStation(ctx context.Context, in *pb.ListAllStationReq) (*pb.ListAllStationResp, error) {
	l := logic.NewListAllStationLogic(ctx, s.svcCtx)
	return l.ListAllStation(in)
}

func (s *TicketServer) RegionTrainStationJob(ctx context.Context, in *pb.RegionTrainStationJobReq) (*pb.RegionTrainStationJobResp, error) {
	l := logic.NewRegionTrainStationJobLogic(ctx, s.svcCtx)
	return l.RegionTrainStationJob(in)
}
