// Code generated by goctl. DO NOT EDIT.

package tPassenger

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	tPassenger0FieldNames = builder.RawFieldNames(&TPassenger0{})
	tPassenger0Rows       = strings.Join(tPassenger0FieldNames, ",")
	// 时间自己处理吧
	tPassenger0RowsExpectAutoSet   = strings.Join(stringx.Remove(tPassenger0FieldNames, "`id`", "`create_at`", "`created_at`", "`update_at`", "`updated_at`"), ",")
	tPassenger0RowsWithPlaceHolder = strings.Join(stringx.Remove(tPassenger0FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`create_date`", "`update_at`", "`updated_at`"), "=?,") + "=?"

	cache12306User0TPassenger0IdPrefix       = "cache:12306User0:tPassenger0:id:"
	cache12306User0TPassenger0UsernamePrefix = "cache:12306User0:tPassenger0:username:"
)

type (
	tPassenger0Model interface {
		FindOne(ctx context.Context, id int64) (*TPassenger0, error)
		Delete(ctx context.Context, session sqlx.Session, id int64, username string) error
		GetPassengerByUserName(ctx context.Context, username string) ([]*TPassenger0, error)
		SelectBuilder() squirrel.SelectBuilder
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		InsertWithTran(ctx context.Context, session sqlx.Session, data *TPassenger0) error
		UpdateWithTran(ctx context.Context, session sqlx.Session, data *TPassenger0) error
	}

	defaultTPassenger0Model struct {
		sqlc.CachedConn
		table string
	}

	TPassenger0 struct {
		Id           int64     `db:"id"`            // ID
		Username     string    `db:"username"`      // 用户名
		RealName     string    `db:"real_name"`     // 真实姓名
		IdType       int64     `db:"id_type"`       // 证件类型
		IdCard       string    `db:"id_card"`       // 证件号码
		DiscountType int64     `db:"discount_type"` // 优惠类型
		Phone        string    `db:"phone"`         // 手机号
		CreateDate   time.Time `db:"create_date"`   // 添加日期
		VerifyStatus int64     `db:"verify_status"` // 审核状态
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 修改时间
		DelFlag      int64     `db:"del_flag"`      // 删除标识
	}
)

func newTPassenger0Model(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTPassenger0Model {
	return &defaultTPassenger0Model{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_passenger_0`",
	}
}

// 删除用户
func (m *defaultTPassenger0Model) Delete(ctx context.Context, session sqlx.Session, id int64, username string) error {
	_12306User0TPassenger0IdKey := fmt.Sprintf("%s%v", cache12306User0TPassenger0IdPrefix, id)
	_12306User0TPassenger0UsernameKey := fmt.Sprintf("%S%v", cache12306User0TPassenger0UsernamePrefix, username)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `del_flag` = ? where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, 1, id)
		}
		return conn.ExecCtx(ctx, query, 1, id)
	}, _12306User0TPassenger0IdKey, _12306User0TPassenger0UsernameKey)
	return err
}

func (m *defaultTPassenger0Model) FindOne(ctx context.Context, id int64) (*TPassenger0, error) {
	_12306User0TPassenger0IdKey := fmt.Sprintf("%s%v", cache12306User0TPassenger0IdPrefix, id)
	var resp TPassenger0
	err := m.QueryRowCtx(ctx, &resp, _12306User0TPassenger0IdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and `del_flag` = 0 limit 1", tPassenger0Rows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTPassenger0Model) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache12306User0TPassenger0IdPrefix, primary)
}

func (m *defaultTPassenger0Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tPassenger0Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTPassenger0Model) tableName() string {
	return m.table
}

// 自定义
func (m *defaultTPassenger0Model) GetPassengerByUserName(ctx context.Context, username string) ([]*TPassenger0, error) {
	var resp []*TPassenger0
	_12306User0TPassenger0UsernameKey := fmt.Sprintf("%S%v", cache12306User0TPassenger0UsernamePrefix, username)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("select %s from %s where `username` = ?", tPassenger0Rows, m.table)
		return nil, conn.QueryRowsCtx(ctx, &resp, query, username)
	}, _12306User0TPassenger0UsernameKey)
	return resp, err
}

func (m *defaultTPassenger0Model) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}

// 事务
func (m *defaultTPassenger0Model) Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultTPassenger0Model) InsertWithTran(ctx context.Context, session sqlx.Session, data *TPassenger0) error {
	// 添加缓存
	_12306User0TPassenger0UsernameKey := fmt.Sprintf("%S%v", cache12306User0TPassenger0UsernamePrefix, data.Username)
	_12306User0TPassenger0IdKey := fmt.Sprintf("%s%v", cache12306User0TPassenger0IdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?,?,?)", m.table, tPassenger0RowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Username, data.RealName, data.IdType, data.IdCard, data.DiscountType, data.Phone, data.CreateDate, data.VerifyStatus, time.Now(), time.Now(), data.DelFlag)
		}
		return conn.ExecCtx(ctx, query, data.Username, data.RealName, data.IdType, data.IdCard, data.DiscountType, data.Phone, data.CreateDate, data.VerifyStatus, time.Now(), time.Now(), data.DelFlag)
	}, _12306User0TPassenger0IdKey, _12306User0TPassenger0UsernameKey)
	return err
}

func (m *defaultTPassenger0Model) UpdateWithTran(ctx context.Context, session sqlx.Session, data *TPassenger0) error {
	// 删除缓存
	_12306User0TPassenger0UsernameKey := fmt.Sprintf("%S%v", cache12306User0TPassenger0UsernamePrefix, data.Username)
	_12306User0TPassenger0IdKey := fmt.Sprintf("%s%v", cache12306User0TPassenger0IdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tPassenger0RowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Username, data.RealName, data.IdType, data.IdCard, data.DiscountType, data.Phone, data.VerifyStatus, data.UpdateTime, data.DelFlag, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Username, data.RealName, data.IdType, data.IdCard, data.DiscountType, data.Phone, data.VerifyStatus, data.UpdateTime, data.DelFlag)
	}, _12306User0TPassenger0IdKey, _12306User0TPassenger0UsernameKey)
	return err
}
