// Code generated by goctl. DO NOT EDIT.

package tTicket

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTicketFieldNames          = builder.RawFieldNames(&TTicket{})
	tTicketRows                = strings.Join(tTicketFieldNames, ",")
	tTicketRowsExpectAutoSet   = strings.Join(stringx.Remove(tTicketFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTicketRowsWithPlaceHolder = strings.Join(stringx.Remove(tTicketFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cache12306TicketTTicketIdPrefix = "cache:12306Ticket:tTicket:id:"
)

type (
	tTicketModel interface {
		Insert(ctx context.Context, data *TTicket) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTicket, error)
		Update(ctx context.Context, data *TTicket) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTicketModel struct {
		sqlc.CachedConn
		table string
	}

	TTicket struct {
		Id             int64          `db:"id"`              // ID
		Username       sql.NullString `db:"username"`        // 用户名
		TrainId        sql.NullInt64  `db:"train_id"`        // 列车ID
		CarriageNumber sql.NullString `db:"carriage_number"` // 车厢号
		SeatNumber     sql.NullString `db:"seat_number"`     // 座位号
		PassengerId    sql.NullInt64  `db:"passenger_id"`    // 乘车人ID
		TicketStatus   sql.NullInt64  `db:"ticket_status"`   // 车票状态
		CreateTime     sql.NullTime   `db:"create_time"`     // 创建时间
		UpdateTime     sql.NullTime   `db:"update_time"`     // 修改时间
		DelFlag        sql.NullInt64  `db:"del_flag"`        // 删除标识
	}
)

func newTTicketModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTicketModel {
	return &defaultTTicketModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_ticket`",
	}
}

func (m *defaultTTicketModel) Delete(ctx context.Context, id int64) error {
	_12306TicketTTicketIdKey := fmt.Sprintf("%s%v", cache12306TicketTTicketIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, _12306TicketTTicketIdKey)
	return err
}

func (m *defaultTTicketModel) FindOne(ctx context.Context, id int64) (*TTicket, error) {
	_12306TicketTTicketIdKey := fmt.Sprintf("%s%v", cache12306TicketTTicketIdPrefix, id)
	var resp TTicket
	err := m.QueryRowCtx(ctx, &resp, _12306TicketTTicketIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTicketRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTicketModel) Insert(ctx context.Context, data *TTicket) (sql.Result, error) {
	_12306TicketTTicketIdKey := fmt.Sprintf("%s%v", cache12306TicketTTicketIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, tTicketRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Username, data.TrainId, data.CarriageNumber, data.SeatNumber, data.PassengerId, data.TicketStatus, data.DelFlag)
	}, _12306TicketTTicketIdKey)
	return ret, err
}

func (m *defaultTTicketModel) Update(ctx context.Context, data *TTicket) error {
	_12306TicketTTicketIdKey := fmt.Sprintf("%s%v", cache12306TicketTTicketIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTicketRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Username, data.TrainId, data.CarriageNumber, data.SeatNumber, data.PassengerId, data.TicketStatus, data.DelFlag, data.Id)
	}, _12306TicketTTicketIdKey)
	return err
}

func (m *defaultTTicketModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache12306TicketTTicketIdPrefix, primary)
}

func (m *defaultTTicketModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTicketRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTicketModel) tableName() string {
	return m.table
}
