// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: ticket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTrainStationQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId string `protobuf:"bytes,1,opt,name=trainId,proto3" json:"trainId,omitempty"`
}

func (x *ListTrainStationQueryReq) Reset() {
	*x = ListTrainStationQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrainStationQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainStationQueryReq) ProtoMessage() {}

func (x *ListTrainStationQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainStationQueryReq.ProtoReflect.Descriptor instead.
func (*ListTrainStationQueryReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *ListTrainStationQueryReq) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

type ListTrainStationQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainStationQueryRespDTO []*TrainStationQueryRespDTO `protobuf:"bytes,1,rep,name=trainStationQueryRespDTO,proto3" json:"trainStationQueryRespDTO,omitempty"`
}

func (x *ListTrainStationQueryResp) Reset() {
	*x = ListTrainStationQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTrainStationQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrainStationQueryResp) ProtoMessage() {}

func (x *ListTrainStationQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrainStationQueryResp.ProtoReflect.Descriptor instead.
func (*ListTrainStationQueryResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *ListTrainStationQueryResp) GetTrainStationQueryRespDTO() []*TrainStationQueryRespDTO {
	if x != nil {
		return x.TrainStationQueryRespDTO
	}
	return nil
}

type TrainStationQueryRespDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 站序
	Sequence string `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// *
	// 站名
	Departure string `protobuf:"bytes,2,opt,name=departure,proto3" json:"departure,omitempty"`
	// *
	// 到站时间
	ArrivalTime string `protobuf:"bytes,3,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	// *
	// 出发时间
	DepartureTime string `protobuf:"bytes,4,opt,name=departureTime,proto3" json:"departureTime,omitempty"`
	// *
	// 停留时间
	StopoverTime int64 `protobuf:"varint,5,opt,name=stopoverTime,proto3" json:"stopoverTime,omitempty"`
}

func (x *TrainStationQueryRespDTO) Reset() {
	*x = TrainStationQueryRespDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainStationQueryRespDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStationQueryRespDTO) ProtoMessage() {}

func (x *TrainStationQueryRespDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStationQueryRespDTO.ProtoReflect.Descriptor instead.
func (*TrainStationQueryRespDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *TrainStationQueryRespDTO) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *TrainStationQueryRespDTO) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *TrainStationQueryRespDTO) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *TrainStationQueryRespDTO) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *TrainStationQueryRespDTO) GetStopoverTime() int64 {
	if x != nil {
		return x.StopoverTime
	}
	return 0
}

type ListRegionStationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryType int64  `protobuf:"varint,1,opt,name=queryType,proto3" json:"queryType,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListRegionStationReq) Reset() {
	*x = ListRegionStationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRegionStationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionStationReq) ProtoMessage() {}

func (x *ListRegionStationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionStationReq.ProtoReflect.Descriptor instead.
func (*ListRegionStationReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *ListRegionStationReq) GetQueryType() int64 {
	if x != nil {
		return x.QueryType
	}
	return 0
}

func (x *ListRegionStationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRegionStationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionStationQueryRespDTO []*RegionStationQueryRespDTO `protobuf:"bytes,1,rep,name=regionStationQueryRespDTO,proto3" json:"regionStationQueryRespDTO,omitempty"`
}

func (x *ListRegionStationResp) Reset() {
	*x = ListRegionStationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRegionStationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegionStationResp) ProtoMessage() {}

func (x *ListRegionStationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegionStationResp.ProtoReflect.Descriptor instead.
func (*ListRegionStationResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *ListRegionStationResp) GetRegionStationQueryRespDTO() []*RegionStationQueryRespDTO {
	if x != nil {
		return x.RegionStationQueryRespDTO
	}
	return nil
}

type RegionStationQueryRespDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// 地区编码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 拼音
	Spell string `protobuf:"bytes,3,opt,name=spell,proto3" json:"spell,omitempty"`
}

func (x *RegionStationQueryRespDTO) Reset() {
	*x = RegionStationQueryRespDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionStationQueryRespDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionStationQueryRespDTO) ProtoMessage() {}

func (x *RegionStationQueryRespDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionStationQueryRespDTO.ProtoReflect.Descriptor instead.
func (*RegionStationQueryRespDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *RegionStationQueryRespDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionStationQueryRespDTO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegionStationQueryRespDTO) GetSpell() string {
	if x != nil {
		return x.Spell
	}
	return ""
}

type ListAllStationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAllStationReq) Reset() {
	*x = ListAllStationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllStationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllStationReq) ProtoMessage() {}

func (x *ListAllStationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllStationReq.ProtoReflect.Descriptor instead.
func (*ListAllStationReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{6}
}

type ListAllStationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationQueryRespDTO []*StationQueryRespDTO `protobuf:"bytes,1,rep,name=stationQueryRespDTO,proto3" json:"stationQueryRespDTO,omitempty"`
}

func (x *ListAllStationResp) Reset() {
	*x = ListAllStationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllStationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllStationResp) ProtoMessage() {}

func (x *ListAllStationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllStationResp.ProtoReflect.Descriptor instead.
func (*ListAllStationResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllStationResp) GetStationQueryRespDTO() []*StationQueryRespDTO {
	if x != nil {
		return x.StationQueryRespDTO
	}
	return nil
}

type StationQueryRespDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// 地区编码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// *
	// 拼音
	Spell string `protobuf:"bytes,3,opt,name=spell,proto3" json:"spell,omitempty"`
	// *
	// 城市名称
	RegionName string `protobuf:"bytes,4,opt,name=regionName,proto3" json:"regionName,omitempty"`
}

func (x *StationQueryRespDTO) Reset() {
	*x = StationQueryRespDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StationQueryRespDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationQueryRespDTO) ProtoMessage() {}

func (x *StationQueryRespDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationQueryRespDTO.ProtoReflect.Descriptor instead.
func (*StationQueryRespDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *StationQueryRespDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StationQueryRespDTO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StationQueryRespDTO) GetSpell() string {
	if x != nil {
		return x.Spell
	}
	return ""
}

func (x *StationQueryRespDTO) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

type RegionTrainStationJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionTrainStationJobReq) Reset() {
	*x = RegionTrainStationJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionTrainStationJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionTrainStationJobReq) ProtoMessage() {}

func (x *RegionTrainStationJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionTrainStationJobReq.ProtoReflect.Descriptor instead.
func (*RegionTrainStationJobReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{9}
}

type RegionTrainStationJobResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionTrainStationJobResp) Reset() {
	*x = RegionTrainStationJobResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionTrainStationJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionTrainStationJobResp) ProtoMessage() {}

func (x *RegionTrainStationJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionTrainStationJobResp.ProtoReflect.Descriptor instead.
func (*RegionTrainStationJobResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{10}
}

type TrainStationDetailJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateTime string `protobuf:"bytes,1,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
}

func (x *TrainStationDetailJobReq) Reset() {
	*x = TrainStationDetailJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainStationDetailJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStationDetailJobReq) ProtoMessage() {}

func (x *TrainStationDetailJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStationDetailJobReq.ProtoReflect.Descriptor instead.
func (*TrainStationDetailJobReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{11}
}

func (x *TrainStationDetailJobReq) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

type TrainStationDetailJobResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrainStationDetailJobResp) Reset() {
	*x = TrainStationDetailJobResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainStationDetailJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainStationDetailJobResp) ProtoMessage() {}

func (x *TrainStationDetailJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainStationDetailJobResp.ProtoReflect.Descriptor instead.
func (*TrainStationDetailJobResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{12}
}

type PageListTicketQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromStation   string `protobuf:"bytes,1,opt,name=fromStation,proto3" json:"fromStation,omitempty"`
	ToStation     string `protobuf:"bytes,2,opt,name=toStation,proto3" json:"toStation,omitempty"`
	DepartureDate string `protobuf:"bytes,3,opt,name=departureDate,proto3" json:"departureDate,omitempty"`
	Departure     string `protobuf:"bytes,4,opt,name=departure,proto3" json:"departure,omitempty"`
	Arrival       string `protobuf:"bytes,5,opt,name=arrival,proto3" json:"arrival,omitempty"`
}

func (x *PageListTicketQueryReq) Reset() {
	*x = PageListTicketQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageListTicketQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageListTicketQueryReq) ProtoMessage() {}

func (x *PageListTicketQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageListTicketQueryReq.ProtoReflect.Descriptor instead.
func (*PageListTicketQueryReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{13}
}

func (x *PageListTicketQueryReq) GetFromStation() string {
	if x != nil {
		return x.FromStation
	}
	return ""
}

func (x *PageListTicketQueryReq) GetToStation() string {
	if x != nil {
		return x.ToStation
	}
	return ""
}

func (x *PageListTicketQueryReq) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *PageListTicketQueryReq) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *PageListTicketQueryReq) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

type PageListTicketQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainList            []*TicketListDTO `protobuf:"bytes,1,rep,name=trainList,proto3" json:"trainList,omitempty"`                         //车次集合数据
	TrainBrandList       []int64          `protobuf:"varint,2,rep,packed,name=trainBrandList,proto3" json:"trainBrandList,omitempty"`       // 车次类型：D-动车 Z-直达 复兴号等
	DepartureStationList []string         `protobuf:"bytes,3,rep,name=departureStationList,proto3" json:"departureStationList,omitempty"`   //出发车站
	ArrivalStationList   []string         `protobuf:"bytes,4,rep,name=arrivalStationList,proto3" json:"arrivalStationList,omitempty"`       //到达车站
	SeatClassTypeList    []int64          `protobuf:"varint,5,rep,packed,name=seatClassTypeList,proto3" json:"seatClassTypeList,omitempty"` // 车次
}

func (x *PageListTicketQueryResp) Reset() {
	*x = PageListTicketQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageListTicketQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageListTicketQueryResp) ProtoMessage() {}

func (x *PageListTicketQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageListTicketQueryResp.ProtoReflect.Descriptor instead.
func (*PageListTicketQueryResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{14}
}

func (x *PageListTicketQueryResp) GetTrainList() []*TicketListDTO {
	if x != nil {
		return x.TrainList
	}
	return nil
}

func (x *PageListTicketQueryResp) GetTrainBrandList() []int64 {
	if x != nil {
		return x.TrainBrandList
	}
	return nil
}

func (x *PageListTicketQueryResp) GetDepartureStationList() []string {
	if x != nil {
		return x.DepartureStationList
	}
	return nil
}

func (x *PageListTicketQueryResp) GetArrivalStationList() []string {
	if x != nil {
		return x.ArrivalStationList
	}
	return nil
}

func (x *PageListTicketQueryResp) GetSeatClassTypeList() []int64 {
	if x != nil {
		return x.SeatClassTypeList
	}
	return nil
}

type TicketListDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 列车 ID
	TrainId string `protobuf:"bytes,1,opt,name=trainId,proto3" json:"trainId,omitempty"`
	// *
	// 车次
	TrainNumber string `protobuf:"bytes,2,opt,name=trainNumber,proto3" json:"trainNumber,omitempty"`
	// *
	// 出发时间
	DepartureTime string `protobuf:"bytes,3,opt,name=departureTime,proto3" json:"departureTime,omitempty"`
	// *
	// 到达时间
	ArrivalTime string `protobuf:"bytes,4,opt,name=arrivalTime,proto3" json:"arrivalTime,omitempty"`
	// *
	// 历时
	Duration string `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	// *
	// 到达天数
	DaysArrived int64 `protobuf:"varint,6,opt,name=daysArrived,proto3" json:"daysArrived,omitempty"`
	// *
	// 出发站点
	Departure string `protobuf:"bytes,7,opt,name=departure,proto3" json:"departure,omitempty"`
	// *
	// 到达站点
	Arrival string `protobuf:"bytes,8,opt,name=arrival,proto3" json:"arrival,omitempty"`
	// *
	// 始发站标识
	DepartureFlag bool `protobuf:"varint,9,opt,name=departureFlag,proto3" json:"departureFlag,omitempty"`
	// *
	// 终点站标识
	ArrivalFlag bool `protobuf:"varint,10,opt,name=arrivalFlag,proto3" json:"arrivalFlag,omitempty"`
	// *
	// 列车类型 0：高铁 1：动车 2：普通车
	TrainType int64 `protobuf:"varint,11,opt,name=trainType,proto3" json:"trainType,omitempty"`
	// *
	// 可售时间
	SaleTime string `protobuf:"bytes,12,opt,name=saleTime,proto3" json:"saleTime,omitempty"`
	// *
	// 销售状态 0：可售 1：不可售 2：未知
	SaleStatus int64 `protobuf:"varint,13,opt,name=saleStatus,proto3" json:"saleStatus,omitempty"`
	// *
	// 列车标签集合 0：复兴号 1：智能动车组 2：静音车厢 3：支持选铺
	TrainTags []string `protobuf:"bytes,14,rep,name=trainTags,proto3" json:"trainTags,omitempty"`
	// *
	// 列车品牌类型 0：GC-高铁/城际 1：D-动车 2：Z-直达 3：T-特快 4：K-快速 5：其他 6：复兴号 7：智能动车组
	TrainBrand string `protobuf:"bytes,15,opt,name=trainBrand,proto3" json:"trainBrand,omitempty"`
	// *
	// 席别实体集合
	SeatClassDTO []*SeatClassDTO `protobuf:"bytes,16,rep,name=seatClassDTO,proto3" json:"seatClassDTO,omitempty"`
}

func (x *TicketListDTO) Reset() {
	*x = TicketListDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketListDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListDTO) ProtoMessage() {}

func (x *TicketListDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListDTO.ProtoReflect.Descriptor instead.
func (*TicketListDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{15}
}

func (x *TicketListDTO) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *TicketListDTO) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

func (x *TicketListDTO) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *TicketListDTO) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *TicketListDTO) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TicketListDTO) GetDaysArrived() int64 {
	if x != nil {
		return x.DaysArrived
	}
	return 0
}

func (x *TicketListDTO) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *TicketListDTO) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

func (x *TicketListDTO) GetDepartureFlag() bool {
	if x != nil {
		return x.DepartureFlag
	}
	return false
}

func (x *TicketListDTO) GetArrivalFlag() bool {
	if x != nil {
		return x.ArrivalFlag
	}
	return false
}

func (x *TicketListDTO) GetTrainType() int64 {
	if x != nil {
		return x.TrainType
	}
	return 0
}

func (x *TicketListDTO) GetSaleTime() string {
	if x != nil {
		return x.SaleTime
	}
	return ""
}

func (x *TicketListDTO) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

func (x *TicketListDTO) GetTrainTags() []string {
	if x != nil {
		return x.TrainTags
	}
	return nil
}

func (x *TicketListDTO) GetTrainBrand() string {
	if x != nil {
		return x.TrainBrand
	}
	return ""
}

func (x *TicketListDTO) GetSeatClassDTO() []*SeatClassDTO {
	if x != nil {
		return x.SeatClassDTO
	}
	return nil
}

type SeatClassDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 席别类型
	Type int64 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// *
	// 席别数量
	Quantity int64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// *
	// 席别价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// *
	// 席别候补标识
	Candidate bool `protobuf:"varint,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *SeatClassDTO) Reset() {
	*x = SeatClassDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatClassDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatClassDTO) ProtoMessage() {}

func (x *SeatClassDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatClassDTO.ProtoReflect.Descriptor instead.
func (*SeatClassDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{16}
}

func (x *SeatClassDTO) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SeatClassDTO) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SeatClassDTO) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatClassDTO) GetCandidate() bool {
	if x != nil {
		return x.Candidate
	}
	return false
}

type PurchaseTicketsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 车次 ID
	TrainId string `protobuf:"bytes,1,opt,name=trainId,proto3" json:"trainId,omitempty"`
	// *
	// 乘车人
	Passengers []*PurchaseTicketPassengerDetailDTO `protobuf:"bytes,2,rep,name=passengers,proto3" json:"passengers,omitempty"`
	// *
	// 选择座位
	ChooseSeats []string `protobuf:"bytes,3,rep,name=chooseSeats,proto3" json:"chooseSeats,omitempty"`
	// *
	// 出发站点
	Departure string `protobuf:"bytes,4,opt,name=departure,proto3" json:"departure,omitempty"`
	// *
	// 到达站点
	Arrival string `protobuf:"bytes,5,opt,name=arrival,proto3" json:"arrival,omitempty"`
}

func (x *PurchaseTicketsReq) Reset() {
	*x = PurchaseTicketsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseTicketsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketsReq) ProtoMessage() {}

func (x *PurchaseTicketsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketsReq.ProtoReflect.Descriptor instead.
func (*PurchaseTicketsReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{17}
}

func (x *PurchaseTicketsReq) GetTrainId() string {
	if x != nil {
		return x.TrainId
	}
	return ""
}

func (x *PurchaseTicketsReq) GetPassengers() []*PurchaseTicketPassengerDetailDTO {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *PurchaseTicketsReq) GetChooseSeats() []string {
	if x != nil {
		return x.ChooseSeats
	}
	return nil
}

func (x *PurchaseTicketsReq) GetDeparture() string {
	if x != nil {
		return x.Departure
	}
	return ""
}

func (x *PurchaseTicketsReq) GetArrival() string {
	if x != nil {
		return x.Arrival
	}
	return ""
}

type PurchaseTicketPassengerDetailDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 乘车人 ID
	PassengerId string `protobuf:"bytes,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	// *
	// 座位类型
	SeatType int64 `protobuf:"varint,2,opt,name=seatType,proto3" json:"seatType,omitempty"`
}

func (x *PurchaseTicketPassengerDetailDTO) Reset() {
	*x = PurchaseTicketPassengerDetailDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseTicketPassengerDetailDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketPassengerDetailDTO) ProtoMessage() {}

func (x *PurchaseTicketPassengerDetailDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketPassengerDetailDTO.ProtoReflect.Descriptor instead.
func (*PurchaseTicketPassengerDetailDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{18}
}

func (x *PurchaseTicketPassengerDetailDTO) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *PurchaseTicketPassengerDetailDTO) GetSeatType() int64 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

type PurchaseTicketsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 订单号
	OrderSn string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	// *
	// 乘车人订单详情
	TicketOrderDetails []*TicketOrderDetailRespDTO `protobuf:"bytes,2,rep,name=ticketOrderDetails,proto3" json:"ticketOrderDetails,omitempty"`
}

func (x *PurchaseTicketsResp) Reset() {
	*x = PurchaseTicketsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseTicketsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketsResp) ProtoMessage() {}

func (x *PurchaseTicketsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketsResp.ProtoReflect.Descriptor instead.
func (*PurchaseTicketsResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{19}
}

func (x *PurchaseTicketsResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PurchaseTicketsResp) GetTicketOrderDetails() []*TicketOrderDetailRespDTO {
	if x != nil {
		return x.TicketOrderDetails
	}
	return nil
}

type TicketOrderDetailRespDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 席别类型
	SeatType int64 `protobuf:"varint,1,opt,name=seatType,proto3" json:"seatType,omitempty"`
	// *
	// 车厢号
	CarriageNumber string `protobuf:"bytes,2,opt,name=carriageNumber,proto3" json:"carriageNumber,omitempty"`
	// *
	// 座位号
	SeatNumber string `protobuf:"bytes,3,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	// *
	// 真实姓名
	RealName string `protobuf:"bytes,4,opt,name=realName,proto3" json:"realName,omitempty"`
	// *
	// 证件类型
	IdType int64 `protobuf:"varint,5,opt,name=idType,proto3" json:"idType,omitempty"`
	// *
	// 证件号
	IdCard string `protobuf:"bytes,6,opt,name=idCard,proto3" json:"idCard,omitempty"`
	// *
	// 车票类型 0：成人 1：儿童 2：学生 3：残疾军人
	TicketType int64 `protobuf:"varint,7,opt,name=ticketType,proto3" json:"ticketType,omitempty"`
	// *
	// 订单金额
	Amount int64 `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *TicketOrderDetailRespDTO) Reset() {
	*x = TicketOrderDetailRespDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketOrderDetailRespDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketOrderDetailRespDTO) ProtoMessage() {}

func (x *TicketOrderDetailRespDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketOrderDetailRespDTO.ProtoReflect.Descriptor instead.
func (*TicketOrderDetailRespDTO) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{20}
}

func (x *TicketOrderDetailRespDTO) GetSeatType() int64 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *TicketOrderDetailRespDTO) GetCarriageNumber() string {
	if x != nil {
		return x.CarriageNumber
	}
	return ""
}

func (x *TicketOrderDetailRespDTO) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *TicketOrderDetailRespDTO) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *TicketOrderDetailRespDTO) GetIdType() int64 {
	if x != nil {
		return x.IdType
	}
	return 0
}

func (x *TicketOrderDetailRespDTO) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *TicketOrderDetailRespDTO) GetTicketType() int64 {
	if x != nil {
		return x.TicketType
	}
	return 0
}

func (x *TicketOrderDetailRespDTO) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CancelTicketOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 订单号
	OrderSn string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
}

func (x *CancelTicketOrderReq) Reset() {
	*x = CancelTicketOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTicketOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketOrderReq) ProtoMessage() {}

func (x *CancelTicketOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketOrderReq.ProtoReflect.Descriptor instead.
func (*CancelTicketOrderReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{21}
}

func (x *CancelTicketOrderReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type CancelTicketOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelTicketOrderResp) Reset() {
	*x = CancelTicketOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTicketOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketOrderResp) ProtoMessage() {}

func (x *CancelTicketOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketOrderResp.ProtoReflect.Descriptor instead.
func (*CancelTicketOrderResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{22}
}

type GetPayInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
}

func (x *GetPayInfoReq) Reset() {
	*x = GetPayInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayInfoReq) ProtoMessage() {}

func (x *GetPayInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayInfoReq.ProtoReflect.Descriptor instead.
func (*GetPayInfoReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{23}
}

func (x *GetPayInfoReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type GetPayInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 订单号
	OrderSn string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	// *
	// 支付总金额
	TotalAmount int64 `protobuf:"varint,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	// *
	// 支付状态
	Status int64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// *
	// 支付时间
	GmtPayment string `protobuf:"bytes,4,opt,name=gmtPayment,proto3" json:"gmtPayment,omitempty"`
}

func (x *GetPayInfoResp) Reset() {
	*x = GetPayInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPayInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayInfoResp) ProtoMessage() {}

func (x *GetPayInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayInfoResp.ProtoReflect.Descriptor instead.
func (*GetPayInfoResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{24}
}

func (x *GetPayInfoResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *GetPayInfoResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetPayInfoResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetPayInfoResp) GetGmtPayment() string {
	if x != nil {
		return x.GmtPayment
	}
	return ""
}

type CommonTicketRefundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 订单号
	OrderSn string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	// *
	// 退款类型 0 部分退款 1 全部退款
	Type int64 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// *
	// 部分退款子订单记录id集合
	SubOrderRecordIdReqList []string `protobuf:"bytes,3,rep,name=subOrderRecordIdReqList,proto3" json:"subOrderRecordIdReqList,omitempty"`
}

func (x *CommonTicketRefundReq) Reset() {
	*x = CommonTicketRefundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonTicketRefundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTicketRefundReq) ProtoMessage() {}

func (x *CommonTicketRefundReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTicketRefundReq.ProtoReflect.Descriptor instead.
func (*CommonTicketRefundReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{25}
}

func (x *CommonTicketRefundReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CommonTicketRefundReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommonTicketRefundReq) GetSubOrderRecordIdReqList() []string {
	if x != nil {
		return x.SubOrderRecordIdReqList
	}
	return nil
}

type CommonTicketRefundResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonTicketRefundResp) Reset() {
	*x = CommonTicketRefundResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonTicketRefundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonTicketRefundResp) ProtoMessage() {}

func (x *CommonTicketRefundResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonTicketRefundResp.ProtoReflect.Descriptor instead.
func (*CommonTicketRefundResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{26}
}

var File_ticket_proto protoreflect.FileDescriptor

var file_ticket_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x34, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x58, 0x0a, 0x18, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54,
	0x4f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x44, 0x54, 0x4f, 0x52, 0x18, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x22,
	0xc0, 0x01, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x72,
	0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5b, 0x0a, 0x19, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44,
	0x54, 0x4f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x52, 0x19, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44,
	0x54, 0x4f, 0x22, 0x59, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x22, 0x13, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x22, 0x5f, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x13, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x52, 0x13,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x54, 0x4f, 0x22, 0x73, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x36, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x22, 0xb6, 0x01, 0x0a, 0x16, 0x50, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x22,
	0x84, 0x02, 0x0a, 0x17, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x09, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x54,
	0x4f, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x14, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x65, 0x61, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x61, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9f, 0x04, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x79, 0x73,
	0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64,
	0x61, 0x79, 0x73, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x75, 0x72, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x72, 0x61,
	0x6e, 0x64, 0x12, 0x34, 0x0a, 0x0c, 0x73, 0x65, 0x61, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44,
	0x54, 0x4f, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x61, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x54, 0x4f, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x54, 0x4f, 0x22, 0x72, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x54, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0xce, 0x01, 0x0a,
	0x12, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x44, 0x0a,
	0x0a, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x44, 0x54, 0x4f, 0x52, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x61,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65,
	0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x22, 0x60, 0x0a,
	0x20, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x54,
	0x4f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x7d, 0x0a, 0x13, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e,
	0x12, 0x4c, 0x0a, 0x12, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x52, 0x12, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x82,
	0x02, 0x0a, 0x18, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x44, 0x54, 0x4f, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73,
	0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x72, 0x69,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x61, 0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x29,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6d, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x6d, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x7f, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x17, 0x73, 0x75, 0x62, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x52, 0x65, 0x71, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x17, 0x73, 0x75, 0x62, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x52, 0x65, 0x71, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x32, 0xbb, 0x06, 0x0a, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x54, 0x0a, 0x15, 0x6c, 0x69, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x11,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x15, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x62,
	0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x1d,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a,
	0x15, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x4a, 0x6f, 0x62, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x13, 0x70, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x11, 0x70, 0x75, 0x72, 0x63, 0x68,
	0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x56, 0x32, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a,
	0x11, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x50, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_proto_rawDescOnce sync.Once
	file_ticket_proto_rawDescData = file_ticket_proto_rawDesc
)

func file_ticket_proto_rawDescGZIP() []byte {
	file_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_proto_rawDescData)
	})
	return file_ticket_proto_rawDescData
}

var file_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_ticket_proto_goTypes = []interface{}{
	(*ListTrainStationQueryReq)(nil),         // 0: pb.ListTrainStationQueryReq
	(*ListTrainStationQueryResp)(nil),        // 1: pb.ListTrainStationQueryResp
	(*TrainStationQueryRespDTO)(nil),         // 2: pb.TrainStationQueryRespDTO
	(*ListRegionStationReq)(nil),             // 3: pb.ListRegionStationReq
	(*ListRegionStationResp)(nil),            // 4: pb.ListRegionStationResp
	(*RegionStationQueryRespDTO)(nil),        // 5: pb.RegionStationQueryRespDTO
	(*ListAllStationReq)(nil),                // 6: pb.ListAllStationReq
	(*ListAllStationResp)(nil),               // 7: pb.ListAllStationResp
	(*StationQueryRespDTO)(nil),              // 8: pb.StationQueryRespDTO
	(*RegionTrainStationJobReq)(nil),         // 9: pb.RegionTrainStationJobReq
	(*RegionTrainStationJobResp)(nil),        // 10: pb.RegionTrainStationJobResp
	(*TrainStationDetailJobReq)(nil),         // 11: pb.TrainStationDetailJobReq
	(*TrainStationDetailJobResp)(nil),        // 12: pb.TrainStationDetailJobResp
	(*PageListTicketQueryReq)(nil),           // 13: pb.PageListTicketQueryReq
	(*PageListTicketQueryResp)(nil),          // 14: pb.PageListTicketQueryResp
	(*TicketListDTO)(nil),                    // 15: pb.TicketListDTO
	(*SeatClassDTO)(nil),                     // 16: pb.SeatClassDTO
	(*PurchaseTicketsReq)(nil),               // 17: pb.PurchaseTicketsReq
	(*PurchaseTicketPassengerDetailDTO)(nil), // 18: pb.PurchaseTicketPassengerDetailDTO
	(*PurchaseTicketsResp)(nil),              // 19: pb.PurchaseTicketsResp
	(*TicketOrderDetailRespDTO)(nil),         // 20: pb.TicketOrderDetailRespDTO
	(*CancelTicketOrderReq)(nil),             // 21: pb.CancelTicketOrderReq
	(*CancelTicketOrderResp)(nil),            // 22: pb.CancelTicketOrderResp
	(*GetPayInfoReq)(nil),                    // 23: pb.GetPayInfoReq
	(*GetPayInfoResp)(nil),                   // 24: pb.GetPayInfoResp
	(*CommonTicketRefundReq)(nil),            // 25: pb.CommonTicketRefundReq
	(*CommonTicketRefundResp)(nil),           // 26: pb.CommonTicketRefundResp
}
var file_ticket_proto_depIdxs = []int32{
	2,  // 0: pb.ListTrainStationQueryResp.trainStationQueryRespDTO:type_name -> pb.TrainStationQueryRespDTO
	5,  // 1: pb.ListRegionStationResp.regionStationQueryRespDTO:type_name -> pb.RegionStationQueryRespDTO
	8,  // 2: pb.ListAllStationResp.stationQueryRespDTO:type_name -> pb.StationQueryRespDTO
	15, // 3: pb.PageListTicketQueryResp.trainList:type_name -> pb.TicketListDTO
	16, // 4: pb.TicketListDTO.seatClassDTO:type_name -> pb.SeatClassDTO
	18, // 5: pb.PurchaseTicketsReq.passengers:type_name -> pb.PurchaseTicketPassengerDetailDTO
	20, // 6: pb.PurchaseTicketsResp.ticketOrderDetails:type_name -> pb.TicketOrderDetailRespDTO
	0,  // 7: pb.ticket.listTrainStationQuery:input_type -> pb.ListTrainStationQueryReq
	3,  // 8: pb.ticket.listRegionStation:input_type -> pb.ListRegionStationReq
	6,  // 9: pb.ticket.listAllStation:input_type -> pb.ListAllStationReq
	9,  // 10: pb.ticket.regionTrainStationJob:input_type -> pb.RegionTrainStationJobReq
	11, // 11: pb.ticket.trainStationDetailJob:input_type -> pb.TrainStationDetailJobReq
	13, // 12: pb.ticket.pageListTicketQuery:input_type -> pb.PageListTicketQueryReq
	17, // 13: pb.ticket.purchaseTickets:input_type -> pb.PurchaseTicketsReq
	17, // 14: pb.ticket.purchaseTicketsV2:input_type -> pb.PurchaseTicketsReq
	21, // 15: pb.ticket.cancelTicketOrder:input_type -> pb.CancelTicketOrderReq
	23, // 16: pb.ticket.getPayInfo:input_type -> pb.GetPayInfoReq
	25, // 17: pb.ticket.commonTicketRefund:input_type -> pb.CommonTicketRefundReq
	1,  // 18: pb.ticket.listTrainStationQuery:output_type -> pb.ListTrainStationQueryResp
	4,  // 19: pb.ticket.listRegionStation:output_type -> pb.ListRegionStationResp
	7,  // 20: pb.ticket.listAllStation:output_type -> pb.ListAllStationResp
	10, // 21: pb.ticket.regionTrainStationJob:output_type -> pb.RegionTrainStationJobResp
	12, // 22: pb.ticket.trainStationDetailJob:output_type -> pb.TrainStationDetailJobResp
	14, // 23: pb.ticket.pageListTicketQuery:output_type -> pb.PageListTicketQueryResp
	19, // 24: pb.ticket.purchaseTickets:output_type -> pb.PurchaseTicketsResp
	19, // 25: pb.ticket.purchaseTicketsV2:output_type -> pb.PurchaseTicketsResp
	22, // 26: pb.ticket.cancelTicketOrder:output_type -> pb.CancelTicketOrderResp
	24, // 27: pb.ticket.getPayInfo:output_type -> pb.GetPayInfoResp
	26, // 28: pb.ticket.commonTicketRefund:output_type -> pb.CommonTicketRefundResp
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ticket_proto_init() }
func file_ticket_proto_init() {
	if File_ticket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrainStationQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTrainStationQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainStationQueryRespDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRegionStationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRegionStationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionStationQueryRespDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllStationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAllStationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StationQueryRespDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionTrainStationJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionTrainStationJobResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainStationDetailJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainStationDetailJobResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageListTicketQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageListTicketQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketListDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatClassDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseTicketsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseTicketPassengerDetailDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseTicketsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketOrderDetailRespDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTicketOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTicketOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPayInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonTicketRefundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonTicketRefundResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_proto_depIdxs,
		MessageInfos:      file_ticket_proto_msgTypes,
	}.Build()
	File_ticket_proto = out.File
	file_ticket_proto_rawDesc = nil
	file_ticket_proto_goTypes = nil
	file_ticket_proto_depIdxs = nil
}
