// Code generated by goctl. DO NOT EDIT.

package tTrainStationRelation

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTrainStationRelationFieldNames          = builder.RawFieldNames(&TTrainStationRelation{})
	tTrainStationRelationRows                = strings.Join(tTrainStationRelationFieldNames, ",")
	tTrainStationRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(tTrainStationRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTrainStationRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(tTrainStationRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cache12306TicketTTrainStationRelationIdPrefix = "cache:12306Ticket:tTrainStationRelation:id:"
)

type (
	tTrainStationRelationModel interface {
		Insert(ctx context.Context, data *TTrainStationRelation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTrainStationRelation, error)
		Update(ctx context.Context, data *TTrainStationRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTrainStationRelationModel struct {
		sqlc.CachedConn
		table string
	}

	TTrainStationRelation struct {
		Id            int64          `db:"id"`             // ID
		TrainId       sql.NullInt64  `db:"train_id"`       // 车次ID
		Departure     sql.NullString `db:"departure"`      // 出发站点
		Arrival       sql.NullString `db:"arrival"`        // 到达站点
		StartRegion   sql.NullString `db:"start_region"`   // 起始城市名称
		EndRegion     sql.NullString `db:"end_region"`     // 终点城市名称
		DepartureFlag sql.NullInt64  `db:"departure_flag"` // 始发标识
		ArrivalFlag   sql.NullInt64  `db:"arrival_flag"`   // 终点标识
		DepartureTime sql.NullTime   `db:"departure_time"` // 出发时间
		ArrivalTime   sql.NullTime   `db:"arrival_time"`   // 到达时间
		CreateTime    sql.NullTime   `db:"create_time"`    // 创建时间
		UpdateTime    sql.NullTime   `db:"update_time"`    // 修改时间
		DelFlag       sql.NullInt64  `db:"del_flag"`       // 删除标识
	}
)

func newTTrainStationRelationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTrainStationRelationModel {
	return &defaultTTrainStationRelationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_train_station_relation`",
	}
}

func (m *defaultTTrainStationRelationModel) Delete(ctx context.Context, id int64) error {
	_12306TicketTTrainStationRelationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationRelationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, _12306TicketTTrainStationRelationIdKey)
	return err
}

func (m *defaultTTrainStationRelationModel) FindOne(ctx context.Context, id int64) (*TTrainStationRelation, error) {
	_12306TicketTTrainStationRelationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationRelationIdPrefix, id)
	var resp TTrainStationRelation
	err := m.QueryRowCtx(ctx, &resp, _12306TicketTTrainStationRelationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationRelationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTrainStationRelationModel) Insert(ctx context.Context, data *TTrainStationRelation) (sql.Result, error) {
	_12306TicketTTrainStationRelationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationRelationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tTrainStationRelationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TrainId, data.Departure, data.Arrival, data.StartRegion, data.EndRegion, data.DepartureFlag, data.ArrivalFlag, data.DepartureTime, data.ArrivalTime, data.DelFlag)
	}, _12306TicketTTrainStationRelationIdKey)
	return ret, err
}

func (m *defaultTTrainStationRelationModel) Update(ctx context.Context, data *TTrainStationRelation) error {
	_12306TicketTTrainStationRelationIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationRelationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTrainStationRelationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TrainId, data.Departure, data.Arrival, data.StartRegion, data.EndRegion, data.DepartureFlag, data.ArrivalFlag, data.DepartureTime, data.ArrivalTime, data.DelFlag, data.Id)
	}, _12306TicketTTrainStationRelationIdKey)
	return err
}

func (m *defaultTTrainStationRelationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache12306TicketTTrainStationRelationIdPrefix, primary)
}

func (m *defaultTTrainStationRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationRelationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTrainStationRelationModel) tableName() string {
	return m.table
}
