// Code generated by goctl. DO NOT EDIT.

package tTrainStationPrice

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tTrainStationPriceFieldNames          = builder.RawFieldNames(&TTrainStationPrice{})
	tTrainStationPriceRows                = strings.Join(tTrainStationPriceFieldNames, ",")
	tTrainStationPriceRowsExpectAutoSet   = strings.Join(stringx.Remove(tTrainStationPriceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tTrainStationPriceRowsWithPlaceHolder = strings.Join(stringx.Remove(tTrainStationPriceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cache12306TicketTTrainStationPriceIdPrefix = "cache:12306Ticket:tTrainStationPrice:id:"
)

type (
	tTrainStationPriceModel interface {
		Insert(ctx context.Context, data *TTrainStationPrice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TTrainStationPrice, error)
		Update(ctx context.Context, data *TTrainStationPrice) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTTrainStationPriceModel struct {
		sqlc.CachedConn
		table string
	}

	TTrainStationPrice struct {
		Id         int64          `db:"id"`          // ID
		TrainId    sql.NullInt64  `db:"train_id"`    // 车次ID
		Departure  sql.NullString `db:"departure"`   // 出发站点
		Arrival    sql.NullString `db:"arrival"`     // 到达站点
		SeatType   sql.NullInt64  `db:"seat_type"`   // 座位类型
		Price      sql.NullInt64  `db:"price"`       // 车票价格
		CreateTime sql.NullTime   `db:"create_time"` // 创建时间
		UpdateTime sql.NullTime   `db:"update_time"` // 修改时间
		DelFlag    sql.NullInt64  `db:"del_flag"`    // 删除标识
	}
)

func newTTrainStationPriceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTTrainStationPriceModel {
	return &defaultTTrainStationPriceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`t_train_station_price`",
	}
}

func (m *defaultTTrainStationPriceModel) Delete(ctx context.Context, id int64) error {
	_12306TicketTTrainStationPriceIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationPriceIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, _12306TicketTTrainStationPriceIdKey)
	return err
}

func (m *defaultTTrainStationPriceModel) FindOne(ctx context.Context, id int64) (*TTrainStationPrice, error) {
	_12306TicketTTrainStationPriceIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationPriceIdPrefix, id)
	var resp TTrainStationPrice
	err := m.QueryRowCtx(ctx, &resp, _12306TicketTTrainStationPriceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationPriceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTTrainStationPriceModel) Insert(ctx context.Context, data *TTrainStationPrice) (sql.Result, error) {
	_12306TicketTTrainStationPriceIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationPriceIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, tTrainStationPriceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TrainId, data.Departure, data.Arrival, data.SeatType, data.Price, data.DelFlag)
	}, _12306TicketTTrainStationPriceIdKey)
	return ret, err
}

func (m *defaultTTrainStationPriceModel) Update(ctx context.Context, data *TTrainStationPrice) error {
	_12306TicketTTrainStationPriceIdKey := fmt.Sprintf("%s%v", cache12306TicketTTrainStationPriceIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tTrainStationPriceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TrainId, data.Departure, data.Arrival, data.SeatType, data.Price, data.DelFlag, data.Id)
	}, _12306TicketTTrainStationPriceIdKey)
	return err
}

func (m *defaultTTrainStationPriceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache12306TicketTTrainStationPriceIdPrefix, primary)
}

func (m *defaultTTrainStationPriceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tTrainStationPriceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTTrainStationPriceModel) tableName() string {
	return m.table
}
